### ISSUE TITLE
Mortality analysis

### ISSUE THREAD

**Issue by essiviippola** [dsgelab/risteys#109]
- [x] run the analysis and export data
- [x] test absolute risk computation with extreme values for all endpoints
- [x] list most deadly endpoints
- [x] calibration against general population
- [x] Mortality counts: make data
- [x] Mortality counts: add to Risteys
- [x] Rephrase mortality case count sentence

**Comment by SaraKuitunen** [comment]
Other issues related to mortality section:
- #189 (In Mortality section, rename "Absolute risk" to "Mortality risk")
- #175 (Update mortality section to work for sex-stratified analysis)

Commits:
- 662d1ea Rephrase mortality counts sentence, grammatic fix
- 3401f0e Fix grammar mistake: "Birth Year" to "Birth year"
- 588bfa3 Handle long endpoint names in Mortality section
-  dcfe976 Add case counts to Mortality section
- c068035 Rename 'Absolute risk' to 'Mortality risk'
- 0af7138 Make clearer representation of Mortality results
- dd54813 Update mortality to use sex-stratified results
- 946ff62 Add interactive mortality section (using FR data)
