### ISSUE TITLE
"Internal server error" with some endpoints

### ISSUE THREAD

**Issue by essiviippola** [dsgelab/risteys#115]
Found these endpoints that give "internal server error" when opening them on Risteys: 

- R18_SUDDEN_INFANT_DEATH_SYNDR
- E4_LESCHNYMAN
- NEONATAL_JAUND_DRUGS_TOXINS_TRANSMIT_MOTHER_GIVEN_NEWBO

**Comment by vincent-octo** [comment]
Thanks for the report!

I am pretty sure this is a duplicate of #94 , so I will close this issue and leave the other open.
Though I am stilling your title because it's better :grimacing:
