### ISSUE TITLE
Survival analysis plot should not be truncated

### ISSUE THREAD

**Issue by vincent-octo** [dsgelab/risteys#127]
There are 2 issues with the current plot:

1. Clipped points if they are at the very top of the Y axis

2. Clipped x labels at the right of the plot

![J10_ASTHMA_bug](https://user-images.githubusercontent.com/4919840/158994052-5e639354-fc17-4ba8-81bc-6d63c4867cba.PNG)

**Comment by essiviippola** [comment]
New way to present survival analysis results
