### ISSUE TITLE
Rename prevalence to period prevalence

### ISSUE THREAD

**Issue by essiviippola** [dsgelab/risteys#143]
Rename "prevalence" to "period prevalence" in the key figures table. 

Need to also add the period (e.g. "period prevalence (1998-xxxx)"). The period should probably come from the data instead of a hard-coded year.

**Comment by SaraKuitunen** [comment]
@essiviippola and @vincent-octo, I understood from Essi that the period for the period prevalence is the coverage of the FinRegistry/ FinnGen data. What are the covered years? Also, to my understanding, there isn't cutting data to start from the same year in the detailed longitudinal data nor in the endpointter program, so are the covered years different for endpoints using data from registries that start in different years?

**Comment by vincent-octo** [comment]
Hey, good question!

The covered years for FinnGen would be 1953–2021 (end of R10). But yes, the registries don't all start in 1953 so it's not super accurate to say the period prevalence is from 1953–2021. For example an endpoint using only the oupatient registry would have a period prevalence 1998–2021.

I would keep it simple though, for example linking "Period prevalence" to [Years covered by the registries](https://risteys.finngen.fi/documentation#explanations-health-registries-coverage-years) doc for Finngen, and similar for FinRegistry?

**Comment by vincent-octo** [comment]
Blocked by #222 .
