### ISSUE TITLE
Draft a layout for a FinnGen+FInRegistry page

### ISSUE THREAD

**Issue by vincent-octo** [dsgelab/risteys#165]
take 30 min to discuss and draft, see what can be done in short term.

Could be done next time Essi visits.

**Comment by essiviippola** [comment]
Here are some ideas for the FR&FG Risteys layout.

The main changes are
1. New sections for the upset plots, key figures, distributions, and CIF (and omit the "Summary Statistics" subtitle)
2. Reorganize the mortality section a bit
3. Clean up the layout by increasing padding and removing some visual clutter 

One additional note: controls include all non-cases for all endpoints, i.e. control definitions are not followed in the new pipeline

![endpoint_definition_plan](https://user-images.githubusercontent.com/25436287/170967428-eb4ae320-2739-4f25-9ed4-cb4115ffc5c6.png)
![summary_stats_plan](https://user-images.githubusercontent.com/25436287/170967444-050f0b2d-d721-4c02-95b8-8ef152f70bb8.png)
![mortality_plan](https://user-images.githubusercontent.com/25436287/170967450-0764426f-2645-4406-bfd5-8236b5b8b0d2.png)
