### ISSUE TITLE
Redesign the DB based on Essi's proposal

### ISSUE THREAD

**Issue by vincent-octo** [dsgelab/risteys#168]
- stratification by sex
- separate tables for each kind of results coming out of the pipeline
- (having dataset columns for result tables)
- [x] @essiviippola to add the diagram here
- [x] make code changes in the Risteys web codebase

Related: #149

**Comment by essiviippola** [comment]
Here's a proposal for the updated database structure

<img width="688" alt="image" src="https://user-images.githubusercontent.com/25436287/172130824-bfcd3af6-7d4e-417a-8f87-6c08e5b8330b.png">
