### ISSUE TITLE
Fix a bug in commit 5bb1e70, issue #137: generate a new random endpoint also when returning to homepage from endpoint page, i.e. without reloading the page.

### ISSUE THREAD

**Issue by SaraKuitunen** [dsgelab/risteys#187]
#137

**Comment by vincent-octo** [comment]
Hei @SaraKuitunen :)

Could you give a bit more context on this one?
For example, could you describe what is the current behevior (with steps to reproduce the bug) and what is your expected behevior.

Thanks!

**Comment by SaraKuitunen** [comment]
Hei,

Sure! Random endpoints are only generated when the page is loaded/ reloaded (sending HTTPS request). A new random endpoint is not generated if user goes from randomly generated endpoint page back to home page by going back to the previous page and then tries to generate another random endpoint. Expected behaviour is that the button to generate random endpoint always generates a new endpoint, also when the button is clicked on already visited homepage to which user has returned. 

Hope this made is clearer! :)
