### ISSUE TITLE
Fix a bug in arrows in endpoint definition.

### ISSUE THREAD

**Issue by SaraKuitunen** [dsgelab/risteys#190]
Arrows in Endpoint definition section are not showing correctly. This might be related to paddings/margins in the box. 

Screenshot showing buggy arrows:
<img width="154" alt="image" src="https://user-images.githubusercontent.com/4919840/183369623-4047abd3-e86e-4c30-b080-de7e5c3c6d4f.png">

**Comment by vincent-octo** [comment]
Won't fix.
We will make a table instead to allow showing both FG and FR easily.
