### ISSUE TITLE
BUG: Invalid sex variable in FinnGen 

### ISSUE THREAD

**Issue by essiviippola** [dsgelab/risteys#191]
The proportion of females and males does not make sense. This only seems to apply to FinnGen. Example: https://risteys.finregistry.fi/endpoint/T2D

**Comment by vincent-octo** [comment]
I will look into it.

Might be some females are classified as males somehow 🤔

**Comment by vincent-octo** [comment]
One of the input files I used to run the pipeline was wrong.
I am re-running the pipeline now with the correct input files to get the sex of the individuals. This should fix the issue when Sara imports the new data.

**Comment by vincent-octo** [comment]
The pipeline run is done and the file has been transferred to @SaraKuitunen . Transferring task assignment to her, as importing this data should fix the issue.

**Comment by SaraKuitunen** [comment]
Importing the new date seemed to fix this issue. I will close this issue now. :)
