### ISSUE TITLE
BUG: Internal Server Error when there are missing values in the key figures

### ISSUE THREAD

**Issue by essiviippola** [dsgelab/risteys#192]
Missing values in the key figures seems to result in Internal Server Error on Risteys.

Examples: 
- https://risteys.finregistry.fi/endpoint/E4_PCOS
- https://risteys.finregistry.fi/endpoint/GEST_DIABETES

**Comment by vincent-octo** [comment]
Closing as it appears to work now =)

**Comment by SaraKuitunen** [comment]
fixed by 8f45cd27fdb132e9e71405a24a4e95a9835d3e27 and 169b9fd5186e7d189fe66863d30c04a0237f944e
