### ISSUE TITLE
Update ontology

### ISSUE THREAD

**Issue by essiviippola** [dsgelab/risteys#193]
- [x] generate a new ontology dataset
- [x] handle multiple codes per endpoint 
- [x] add the new data to the portal
- [x] add a section for ontology on the documentation page

**Comment by vincent-octo** [comment]
Hi @essiviippola , could you remind me how the generation of the new ontology is done?
Is it from Feiyi's code and data?

Kiitos :v:

**Comment by essiviippola** [comment]
Here's the documentation that I have shared with @SaraKuitunen to be added to the documentation page: 

"Endpoints are linked to international ontologies DOID, MESH, and EFO, and links to the ontologies are presented on Risteys when available. The mapping is carried out using an automated algorithm followed by manual curation. 

First, the following hierarchical algorithm is used to link endpoints to DOID and MESH codes: 
1. ICD-10 codes are matched to DOID ICD-10-CM codes 
2. endpoint names are matched to DOID names and synonyms 
3. endpoints are matched to MESH codes and converted to DOID 
4. ICD-10 codes are matched one step up in the ICD-10 hierarchy 
5. endpoint names are matched with DOID codes using the Ratcliff/Obershelp pattern matching (similarity > 0.69)
The resulting DOID and MESH codes are mapped to EFO when a mapping is available. 

Next, the fuzzy matching algorithm [OnToma](https://github.com/opentargets/OnToma) and the ontology annotations for endpoints available on the [Open Targets](https://www.opentargets.org/) portal are used to link endpoints to EFO codes. 

Finally, endpoints with discordant EFO annotations between the existing mappings, OnToma, and Open Targets are manually checked and corrected."
