### ISSUE TITLE
[major change] variable length of follow-up in the association analysis

### ISSUE THREAD

**Issue by andgan** [dsgelab/risteys#20]
It should be possible to filter on 1 year, 5 years, 10 years distance between the two diseases, similar to what done in the NB-COMO project. The cut-off can be also decided after inspecting the distribution of time difference between diseases

**Comment by vincent-octo** [comment]
This depends on:
- #38 Find time-points for lagged HRs
- #39 Implement lagged HRs in the pipeline
- #40 Test lagged HRs using a small sample of associations
- #41 Adapt DB and import script for lagged HRs
- #42 Adapt Risteys to show lagged HRs

**Comment by vincent-octo** [comment]
Done.
To be release in v1.7.0
