### ISSUE TITLE
Handle non-core endpoints the same way as in FinnGen Risteys

### ISSUE THREAD

**Issue by SaraKuitunen** [dsgelab/risteys#220]

**Comment by vincent-octo** [comment]
Sorry I forgot: could you remind me how this issues differs from #215? Thanks 🙌

**Comment by SaraKuitunen** [comment]
#215 removes from the database such endpoints that are not supposed to be in the portal (F5_SAD is excluded because it's seasonal & other have omit=2 value in the endpoint controls file).

This issue is to show the info banner for non-core endpoints and to point to a counterpart endpoint that is core endpoint, if such endpoint exists. I have this issue for FR-FG Risteys now because this was implemented in FinnGen Risteys R9 but at that time I wasn't able to have it in FR-FG Risteys because it was for R8 data and thus endpoints didn't have core or non-core statuses.

**Comment by vincent-octo** [comment]
Oh, right! Thanks for the explanation 😃

**Comment by SaraKuitunen** [comment]
Solved by bddb859f
