### ISSUE TITLE
How to get dataset full data table?

### ISSUE THREAD

**Issue by ZhengGongwei** [dsgelab/risteys#228]
How can I see the details of R5(https://r5.risteys.finngen.fi//phenocode/H7_RETINOPATHYDIAB#endpoint-definition) dataset? I can see it in R8(https://r8.risteys.finngen.fi/phenocode/H7_RETINOPATHYDIAB#correlations) 'Endpoint definition' section.
Thanks!

**Comment by ZhengGongwei** [comment]
I want to know why the dataset has the H7 label, and what is the difference between it and other diabetic retinopathy datasets?

**Comment by vincent-octo** [comment]
Hi,

Many endpoints are defined using the ICD-10 system (actually [a variant](https://www.julkari.fi/bitstream/handle/10024/80324/15c30d65-2b96-41d7-aca8-1a05aa8a0a19.pdf?sequence=1&isAllowed=y) of it for Finland). This ICD-10 system has codes that starts with a later (e.g. `J10.8`).
The `H7_` label refers to the chapter with codes starting with `H`, which is also chapter `7`.

Regarding your first question, you can find the endpoint definitions in full for all releases here: https://www.finngen.fi/en/researchers/clinical-endpoints

Let me know if you have other questions
