### ISSUE TITLE
Please consult Mendelian randomization：gestational diabetes

### ISSUE THREAD

**Issue by jiayy2018puluo** [dsgelab/risteys#241]
Mendelian randomization: I did a two sample Mendelian randomization randomization study, and the outcome indicator was gestational diabetes. The data for outcome indicators were obtained from the Finnish database version R9. But now the result of Mendelian randomization is negative. I am thinking about the reasons that led to a negative outcome. My research object is pregnant women. Do I need to screen out those who have given birth in the downloaded data? How to exclude people who have not been pregnant or had children from Finnish databases？So how to filter? Can you give me some guidance? Thank you.

**Comment by vincent-octo** [comment]
Hello, thanks for your question.

Accessing individual-level data — such as pregnancy status for each FinnGen participants — is only possible with a so called FinnGen "red" account.

You can find more infomation here about accessing FinnGen data here: https://finngen.gitbook.io/finngen-handbook/where-to-begin.../how-to-request-an-account

Hope this helps!
