### ISSUE TITLE
data download

### ISSUE THREAD

**Issue by stevenlehrer** [dsgelab/risteys#243]
I was able to download 
AB1_VIRAL_CNS
with
wget https://storage.googleapis.com/finngen-public-data-r2/summary_stats/finngen_r2_AB1_VIRAL_CNS.gz
How do I download
AB1_VIRAL_ENCEPHALITIS_NOS

**Comment by vincent-octo** [comment]
Here are a couple of links that should help you get started:

- Description of the summary statistics file that you downloaded https://finngen.gitbook.io/documentation/data-description

- Overview of what is a GWAS https://finngen.gitbook.io/finngen-handbook/background-reading/gwas-analysis 

- In-depth article about GWAS https://www.nature.com/articles/s43586-021-00056-9
