### ISSUE TITLE
add category classification from pheweb

### ISSUE THREAD

**Issue by andgan** [dsgelab/risteys#48]
Hi In the phewb phewas browser they have a more detailed classification of disease categories (e.g. disease of the digestive system etc...) that we have in risteys. Since we use the same endpoints, can we have the same classification?

**Comment by vincent-octo** [comment]
Disease categories should be the same already :thinking: … Though in the association plot we display only the top 10-12 categories I think, in order to keep it readable. Happy to look at a specific example if you have one!
Unfortunately these categories were set in DF2 and not updated afterwards.

**Comment by vincent-octo** [comment]
Categories have been added for R5 data, we should rely on this new ones for Risteys R5.
