### ISSUE TITLE
Sketch ideas for switching between different datasets

### ISSUE THREAD

**Issue by vincent-octo** [dsgelab/risteys#64]
It is possible to view different datasets with Risteys, but one has to know the URLs:
- r6.risteys.finngen.fi
- r5.risteys.finngen.fi
- r4.risteys.finngen.fi
- r3.risteys.finngen.fi
which is not obvious.

Happy to hear some ideas on making users aware that other datasets are available, and to provide them a way to switch between these datasets.
(No need to code the ideas, an image or a slide is fine!)

---

Let's work on that task together after the holidays :)

**Comment by vincent-octo** [comment]
Hey @SaraKuitunen , could you remind me the status of this task :) ?

I remember you made good work on the branch https://github.com/dsgelab/risteys/tree/switch_releases, but I don't remember what is left to do.

Thanks

**Comment by SaraKuitunen** [comment]
Hi,

If I remember correctly, the plan was that you double-check the code, and
if it's good, we push it online together.

-Sara

ti 31. elok. 2021 klo 13.20 vincent ***@***.***) kirjoitti:

**Comment by vincent-octo** [comment]
Closed c376667d0d44494636f63631a733f1644bfa85c4
