### ISSUE TITLE
format description for EHR/EMR input file

### ISSUE THREAD

**Issue by Shicheng-Guo** [dsgelab/risteys#78]
Dear Vincent, Sara and Risteys team: 
 
I am wondering is there any page to share format of EHR/EMR input file. I am trying to use this platform for some other cohort, but I am not sure what exact format for the EHR/EMR input file should be prepared. 

Thanks. 

Shicheng

**Comment by vincent-octo** [comment]
Hello Schicheng :wave: !

Thanks for contacting us, it is exciting to have people use this project!

Probably the best resource would be found in the [FinnGen analyst handbook](https://app.gitbook.com/@finngen/s/finngen-analyst-handbook/), especially these relevant articles:
- [Phenotype files in Sandbox](https://finngen.gitbook.io/finngen-analyst-handbook/finngen-data-specifics/finnish-health-registers-and-medical-coding/what-phenotype-files-are-available-in-sandbox-1)
- [Interpretation of the Endpoint Definition file](https://finngen.gitbook.io/finngen-analyst-handbook/finngen-data-specifics/endpoints/how-to-interpret-endpoint-definition-file)

Hope this helps :slightly_smiling_face: .

**Comment by Shicheng-Guo** [comment]
Thank you so much, Vicent!! This information is quite helpful. I will check carefully for the format. 

Shicheng
